package formularios;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import restaurante.clases.Render;
 

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ANDY
 */
public class Menu extends javax.swing.JFrame {

    /**
     * z
     * Creates new form Menu
     */
    String Tipo = "";
    int id=-1;
    File Menus = new File("menus.txt");
    File ingredientes = new File("ingredeintes.txt");
    File im = new File("ingredientes-menu.txt");
 
    int x,y;
 
     DefaultTableModel model3 = new DefaultTableModel(new Object[][]{}, new Object[]{"Mesa", "Estado"}
    ) {
        public boolean isCellEditable(int Row, int Column) {
            return false;

        }
    };
    ArrayList<restaurante.clases.pedido> platosapedir = new ArrayList<restaurante.clases.pedido>();
    ArrayList<restaurante.clases.pedido> platosapedir2 = new ArrayList<restaurante.clases.pedido>();
    DefaultListModel modelo2 = new DefaultListModel();
    DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new Object[]{"", "", ""}
    ) {
        public boolean isCellEditable(int Row, int Column) {
            return false;

        }
    };
funciones.user mesero;
    public Menu(funciones.user u) {
mesero=u;
        initComponents();
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setPreferredSize(new Dimension(0, 0));
         funciones.solonumeros(mesa);
         funciones.sololetras(cliente);
         meserotext.setText(u.nombre);
        this.setLocationRelativeTo(null); 
        listapedidos.setDefaultRenderer(Object.class,new  color());
        tabla.getTableHeader().setDefaultRenderer(renderer);
        tabla.setDefaultRenderer(Object.class, new Render());
        tabla.setVisible(false);
        model3.setRowCount(0);
        if (!funciones.ord.isEmpty()) {
            for (int i = 0; i < u.ordenes.size(); i++) {
                model3.addRow(new Object[]{u.ordenes.get(i).getMesa(), u.ordenes.get(i).getEstado()});
            }
            listapedidos.setModel(model3);
        }

        tabla.setRowHeight(30);

    }
    public void actualizar(funciones.user u){
    if (!funciones.ord.isEmpty()) {
         model3.setRowCount(0);
            for (int i = 0; i < u.ordenes.size(); i++) {
                model3.addRow(new Object[]{u.ordenes.get(i).getMesa(), u.ordenes.get(i).getEstado()});
            }
            listapedidos.setModel(model3);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        bebidas = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        postre = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        platos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Aceptar_LimiteBTN = new javax.swing.JButton();
        mesa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listapedidos = new javax.swing.JTable();
        Aceptar_LimiteBTN1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        meserotext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 204, 186));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 23, 16));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 23, 16));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setBackground(new java.awt.Color(51, 23, 16));
        tabla.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabla.setForeground(new java.awt.Color(255, 255, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"hh", "hhh", "hh", "hh"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, -1, 129));

        bebidas.setBackground(new java.awt.Color(255, 255, 255));
        bebidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bebidasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bebidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bebidasMouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 23, 16));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/Beverage-Milk-Shake.png"))); // NOI18N
        jLabel10.setText("Bebidas");

        jSeparator3.setBackground(new java.awt.Color(51, 23, 16));

        javax.swing.GroupLayout bebidasLayout = new javax.swing.GroupLayout(bebidas);
        bebidas.setLayout(bebidasLayout);
        bebidasLayout.setHorizontalGroup(
            bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        bebidasLayout.setVerticalGroup(
            bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bebidasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(bebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 11, -1, -1));

        postre.setBackground(new java.awt.Color(255, 255, 255));
        postre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        postre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                postreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                postreMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(51, 23, 16));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 23, 16));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/Ice-Cream-03.png"))); // NOI18N
        jLabel9.setText("Postres");

        jSeparator2.setBackground(new java.awt.Color(51, 23, 16));

        javax.swing.GroupLayout postreLayout = new javax.swing.GroupLayout(postre);
        postre.setLayout(postreLayout);
        postreLayout.setHorizontalGroup(
            postreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, postreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(24, 24, 24))
        );
        postreLayout.setVerticalGroup(
            postreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(postre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 11, 150, -1));

        platos.setBackground(new java.awt.Color(255, 255, 255));
        platos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        platos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                platosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                platosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                platosMouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(51, 23, 16));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 23, 16));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/Seafood-Fish.png"))); // NOI18N
        jLabel8.setText("Platos");

        jSeparator1.setBackground(new java.awt.Color(51, 23, 16));

        javax.swing.GroupLayout platosLayout = new javax.swing.GroupLayout(platos);
        platos.setLayout(platosLayout);
        platosLayout.setHorizontalGroup(
            platosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, platosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(38, 38, 38))
        );
        platosLayout.setVerticalGroup(
            platosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(platosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(platos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 170, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jPanel6.setBackground(new java.awt.Color(220, 204, 186));
        jPanel6.setPreferredSize(new java.awt.Dimension(510, 300));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(80, 34, 23));
        jLabel12.setText("La Prosperidad");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/Beverage-Coffee-01.png"))); // NOI18N
        jLabel14.setText(" ");

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(80, 34, 23));
        jLabel15.setText("Andy Arias & ivan candena");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(171, 171, 171))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 493, 473));

        jPanel2.setBackground(new java.awt.Color(220, 204, 186));
        jPanel2.setForeground(new java.awt.Color(220, 204, 186));

        jPanel3.setBackground(new java.awt.Color(51, 23, 16));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/list.png"))); // NOI18N
        jLabel4.setText("Lista de Pedidos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jScrollPane2.setViewportView(jList1);

        Aceptar_LimiteBTN.setBackground(new java.awt.Color(51, 23, 16));
        Aceptar_LimiteBTN.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar_LimiteBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/Add-New.png"))); // NOI18N
        Aceptar_LimiteBTN.setText("Solicitar Pedido");
        Aceptar_LimiteBTN.setBorder(null);
        Aceptar_LimiteBTN.setBorderPainted(false);
        Aceptar_LimiteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aceptar_LimiteBTNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/mesa.png"))); // NOI18N

        cliente.setText(" ");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/icocliente.png"))); // NOI18N

        listapedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mesa", "Estado", "Platos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listapedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listapedidosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listapedidos);

        Aceptar_LimiteBTN1.setBackground(new java.awt.Color(51, 23, 16));
        Aceptar_LimiteBTN1.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar_LimiteBTN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/back.png"))); // NOI18N
        Aceptar_LimiteBTN1.setText("Volver ");
        Aceptar_LimiteBTN1.setBorder(null);
        Aceptar_LimiteBTN1.setBorderPainted(false);
        Aceptar_LimiteBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aceptar_LimiteBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Aceptar_LimiteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Aceptar_LimiteBTN1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Aceptar_LimiteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Aceptar_LimiteBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setBackground(new java.awt.Color(255, 51, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/caafe2.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Restaurante la prosperidad");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mesero:");

        meserotext.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        meserotext.setForeground(new java.awt.Color(255, 255, 255));
        meserotext.setText("Holaaaa");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meserotext, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meserotext)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel5MouseExited

    private void platosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_platosMouseClicked
        // TODO add your handling code here:
        Tipo = "Platos";
        model.setNumRows(0);
        ArrayList<restaurante.clases.pedido> platos = new ArrayList<restaurante.clases.pedido>();
        platos = funciones.buscarplatos("Platos", Menus);
        JButton btn = new JButton("Añadir a pedido");
        for (int i = 0; i < platos.size(); i++) {
            model.addRow(new Object[]{platos.get(i).getNombre(), "$" + platos.get(i).getPrecio(), btn});
        }

        tabla.setModel(model);
        tabla.setVisible(true);
        System.out.println("hola");
    }//GEN-LAST:event_platosMouseClicked

    private void platosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_platosMouseEntered
        platos.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_platosMouseEntered

    private void platosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_platosMouseExited
        platos.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(51, 23, 16));


    }//GEN-LAST:event_platosMouseExited

    private void postreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postreMouseEntered
        // TODO add your handling code here:
        postre.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_postreMouseEntered

    private void postreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postreMouseExited
        // TODO add your handling code here:
        postre.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(51, 23, 16));

    }//GEN-LAST:event_postreMouseExited

    private void bebidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bebidasMouseEntered
        bebidas.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_bebidasMouseEntered

    private void bebidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bebidasMouseExited
        bebidas.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(51, 23, 16));
    }//GEN-LAST:event_bebidasMouseExited

    private void postreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postreMouseClicked
        // TODO add your handling code here:
        Tipo = "Postres";
        model.setNumRows(0);
        ArrayList<restaurante.clases.pedido> platos = new ArrayList<restaurante.clases.pedido>();
        platos = funciones.buscarplatos("Postres", Menus);
        JButton btn = new JButton("Añadir a pedido");
        for (int i = 0; i < platos.size(); i++) {
            model.addRow(new Object[]{platos.get(i).getNombre(), "$" + platos.get(i).getPrecio(), btn});
        }

        tabla.setModel(model);
        tabla.setVisible(true);
        System.out.println("hola");
    }//GEN-LAST:event_postreMouseClicked

    private void bebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bebidasMouseClicked
        // TODO add your handling code here:
        model.setNumRows(0);
        Tipo = "Bebidas";
        ArrayList<restaurante.clases.pedido> platos = new ArrayList<restaurante.clases.pedido>();
        platos = funciones.buscarplatos("Bebidas", Menus);
        JButton btn = new JButton("Añadir a pedido");
        for (int i = 0; i < platos.size(); i++) {
            model.addRow(new Object[]{platos.get(i).getNombre(), "$" + platos.get(i).getPrecio(), btn});
        }

        tabla.setModel(model);
        tabla.setVisible(true);
        System.out.println("hola");
    }//GEN-LAST:event_bebidasMouseClicked

    private void Aceptar_LimiteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aceptar_LimiteBTNActionPerformed
        if (!mesa.getText().equals("") && !cliente.getText().equals("") &&!modelo2.isEmpty()) {
            
            int m=Integer.parseInt(mesa.getText());
            int indice=funciones.indicep(m);
            if (indice>-1) {
                 ArrayList<restaurante.clases.pedido> nuevosp= new ArrayList<restaurante.clases.pedido>();
                for (int i = 0; i < funciones.ord.get(indice).getPedidos().size(); i++) {
                    nuevosp.add(funciones.ord.get(indice).getPedidos().get(i));
                }
                for (int i = 0; i < platosapedir.size(); i++) {
                    platosapedir.get(i).setId(platosapedir.get(i).getId()+funciones.ord.get(indice).getPedidos().size());
               nuevosp.add(platosapedir.get(i));
              
            }
                
                 mesero.ordenes.clear();
                
                funciones.ord.get(indice).setPedidos(nuevosp); 
             mesero.ordenes.add(funciones.ord.get(indice));
            funciones.mostrarmensaje("Agregados A pedidos", "nuevos pedidos agregador a la mesa:"+mesa.getText(), this);
         platosapedir.clear();
                 mesa.setText("");
  modelo2.clear();
            cliente.setText("");
            }else{
            
             restaurante.clases.orden o = new restaurante.clases.orden();
            ArrayList<restaurante.clases.pedido> platosapedir2 = new ArrayList<restaurante.clases.pedido>();
            o.setCliente(cliente.getText());
            o.setMesa(Integer.parseInt(mesa.getText()));
            o.setEstado("Pendiente");
            id=-1;
            for (int i = 0; i < platosapedir.size(); i++) {
                platosapedir2.add(platosapedir.get(i));
            }

            o.setPedidos(platosapedir2);
            mesero.nummesas=mesero.nummesas+1;
            mesero.ordenes.add(o);
            funciones.ord.add(o);
                System.out.println("hola"+ funciones.meseros.nombre);
           
            mesa.setText("");

            cliente.setText("");
            modelo2.clear();
            model3.addRow(new Object[]{o.getMesa(), "Pendiente"});
            listapedidos.setModel(model3);
            platosapedir.clear();
            
            }

           
        } else {

            funciones.mostrarError("falta Mesa y cliente", "Complete los datos ", this);
        }
    }//GEN-LAST:event_Aceptar_LimiteBTNActionPerformed
 
    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

        int r = tabla.getSelectedRow();
        System.out.println(r);
        int c = tabla.getColumnModel().getColumnIndexAtX(evt.getX());
        Object value = tabla.getValueAt(r, c);
        if (value instanceof JButton) {
            ((JButton) value).doClick();
            if (funciones.puedeordenar(tabla.getValueAt(r, 0).toString(), im)) {
                restaurante.clases.pedido p = new restaurante.clases.pedido();
            p.setNombre(tabla.getValueAt(r, 0).toString());
            p.setTipo(Tipo);
            id++;
            p.setListo("Pendiente");
            p.setId(id);
            p.setPrecio(Double.parseDouble(tabla.getValueAt(r, 1).toString().substring(1, tabla.getValueAt(r, 1).toString().length())));
            modelo2.addElement(tabla.getValueAt(r, 0));
            jList1.setModel(modelo2);
            platosapedir.add(p); 
            }else{
            funciones.mostrarError("No es posible", "No hay suficiente productos en Stok para este plato ", this);
            }
           

        }
    }//GEN-LAST:event_tablaMouseClicked

    private void Aceptar_LimiteBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aceptar_LimiteBTN1ActionPerformed
        this.setVisible(false);
        login l = new login();
        l.setLocationRelativeTo(null);
        l.setVisible(true);

    }//GEN-LAST:event_Aceptar_LimiteBTN1ActionPerformed

    private void listapedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listapedidosMouseClicked
       int r= listapedidos.getSelectedRow();
        // ivan mira ya paso todo por parametro para que hagas la factura solo es llenar la tabla aquiella y generar la factura que me imagino que la vas a generar como PDF
        System.out.println(r);
        
        int cont = 0;
        for (int i = 0; i < funciones.ord.size(); i++) {

            if (funciones.ord.get(i).getMesa() == Integer.parseInt(listapedidos.getValueAt(r, 0).toString())) {
                cont = i;
            }
        }

        int mesa = funciones.ord.get(cont).getMesa();
        String Cliente = funciones.ord.get(cont).getCliente();
        String estado = funciones.ord.get(cont).getEstado();

        ArrayList<restaurante.clases.pedido> pla = funciones.ord.get(cont).getPedidos();
        if (estado.equals("Cocinando")) {
            Factura f = new Factura(mesa, Cliente, pla,mesero,this);
            f.setVisible(true);
        } else {
            if(estado.equals("Listo")){
            funciones.mostrarError("Plato ya  listo", "El plato esta listo ", this);

            
            
            }else{
                 funciones.mostrarError("Plato no listo", "El plato aun no esta listo ", this);

            }
               }


    }//GEN-LAST:event_listapedidosMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
      Point point = MouseInfo.getPointerInfo().getLocation();
                setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
                y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar_LimiteBTN;
    private javax.swing.JButton Aceptar_LimiteBTN1;
    private javax.swing.JPanel bebidas;
    private javax.swing.JTextField cliente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable listapedidos;
    private javax.swing.JTextField mesa;
    private javax.swing.JLabel meserotext;
    private javax.swing.JPanel platos;
    private javax.swing.JPanel postre;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
